import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/navbar";

const defaultFont = localFont({
  src: "../public/fonts/Satoshi-Regular.otf",
  weight: "400",
  style: "normal",
});

const headingFont = localFont({
  src: "../public/fonts/Bevellier-Medium.otf",
  weight: "500",
  style: "normal",
  variable: "--font-heading",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${defaultFont.className} ${headingFont.variable} antialiased h-dvh w-screen overflow-x-hidden`}
      >
        <Navbar />
        <main className="h-[calc(100dvh-4rem)] container mx-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
